name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and Push Golang
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: f7star/golang:v1.21  # 替换为你的 Docker Hub 用户名和仓库
        file: ./golang/Dockerfile  # 确保你的项目中有 Dockerfile
      
